"""Initial migration.

Revision ID: 60149994ae7f
Revises: 
Create Date: 2024-08-04 22:13:08.606405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60149994ae7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber')
    # ### end Alembic commands ###
